<?php

$config['system.site']['uuid'] = 'dd7496e0-fd37-4376-ae8e-dfe2c4b01dc2';
$config['language.entity.en']['uuid'] = 'ee2273b2-bd1e-4874-b158-66e70b7904de';

$settings['hash_salt'] = '3tb-0Ud41gJ1JU8iHhiatCxQBLfsaU70-s-JgTluFliAkCFVPR101gs9VgTxoT0HB5rBDg_Qlw';

$databases['default']['default'] = array (
    'database' => 'dev-soen',
    'username' => 'dev-db-admin',
    'password' => 'm{&{;dFyT%+_',
    'prefix' => '',
    'host' => 'localhost',
    'port' => '3306',
    'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
    'driver' => 'mysql',
  );
