<?php

/**
 * Implements hook_theme().
 */
function soen_global_theme($existing, $type, $theme, $path) {

    return [		
      // Name of the theme hook. This is used in the controller to trigger the hook.
      'l1_page_markup' => [
        'render element' => 'children',
        'template' => 'l1-page',
        'path' => $path . '/templates',
        'variables' => [
          'headline' => '',
          'subheadline' => '',
          'parentTerms' => [],
          'parentTermGroup' => 0,
          'parentTermGroup2' => 0,
          'mainContent' => [],
          'defaultTerm' => 0,
          'defaultPoster' => [],
        ],
      ],
    ];
  
  }