<?php

/**
 * @file
 * Module file for views_infinite_scroll.
 */

use Drupal\Core\Url;
use Drupal\Core\Template\Attribute;
use Drupal\views_infinite_scroll\Plugin\views\pager\InfiniteScroll;

/**
 * Implements hook_preprocess_views_infinite_scroll_pager().
 */
function views_infinite_scroll_preprocess_views_infinite_scroll_pager(&$vars) {
  // The important parts we needed lifted wholesale from
  // template_preprocess_views_mini_pager().
  /** @var \Drupal\Core\Pager\PagerManagerInterface $pager_manager */
  $pager_manager = \Drupal::service('pager.manager');
  $element = $vars['element'];
  $parameters = $vars['parameters'];
  $pager = $pager_manager->getPager($element);

  if (isset($pager) && $pager->getCurrentPage() < ($pager->getTotalPages() - 1)) {
    $options = array(
      'query' => $pager_manager->getUpdatedParameters($parameters, $element, $pager->getCurrentPage() + 1),
    );
    $vars['items']['next']['href'] = Url::fromRoute('<none>', [], $options);
  }
  $vars['#cache']['contexts'][] = 'url.query_args';
  $vars['attributes'] = new Attribute([
    'class' => ['js-pager__items', 'pager'],
    'data-drupal-views-infinite-scroll-pager' => $vars['options']['automatically_load_content'] ? 'automatic' : TRUE,
  ]);

}

/**
 * Check if view has InfiniteScroll pager and return content_wrapper option.
 */
function _views_infinite_scroll_get_content_wrapper(&$vars) {
  $view = $vars['view'];
  if ($view->getDisplay()->isPagerEnabled() && !empty($vars['rows'])) {
    $pager = $view->getPager();
    if ($pager && $pager instanceof InfiniteScroll) {
      return $pager->options['views_infinite_scroll']['content_wrapper'];
    }
  }
  return FALSE;
}

/**
 * Implements hook_preprocess_views_view().
 */
function views_infinite_scroll_preprocess_views_view(&$vars) {
  if (_views_infinite_scroll_get_content_wrapper($vars) == 'container') {
      if (!isset($vars['rows']['#theme_wrappers'])) {
        $vars['rows']['#theme_wrappers'] = [];
      }
      $vars['rows']['#theme_wrappers']['container'] = [
        '#attributes' => [
          'data-drupal-views-infinite-scroll-content-wrapper' => TRUE,
          'class' => [
            'views-infinite-scroll-content-wrapper',
            'clearfix',
          ],
        ],
      ];
    }
  }

/**
 * Implements hook_preprocess_views_view_list().
 */
function views_infinite_scroll_preprocess_views_view_list(&$vars) {
  if (_views_infinite_scroll_get_content_wrapper($vars) == 'list') {
    $vars['list']['attributes']['data-drupal-views-infinite-scroll-content-wrapper'] = TRUE;
    $vars['list']['attributes']['class'][] = 'views-infinite-scroll-content-wrapper';
  }
}
