block.settings.bs_lib_navigation_bar_toggler_block:
  type: block_settings
  label: 'Navigation bar toggler block settings'
  mapping:
    toggle_label:
      type: label
      label: 'Label'

block.settings.bs_lib_scroll_to_top_block:
  type: block_settings
  label: 'Scroll to top settings'
  mapping:
    css_class:
      type: string
      label: 'CSS classes'
    duration:
      type: integer
      label: 'Scroll duration in milliseconds'
    easing:
      type: string
      label: 'Easing function'
    offset:
      type: string
      label: 'Browser window scroll offset when scroll to top is shown'
    offset_opacity:
      type: string
      label: 'Browser window scroll offset when scroll to top is shown with opacity'
    position:
      type: string
      label: 'Scroll to top position on the page'
    position_fixed_disable_element:
      type: string
      label: 'CSS selector of element for which fixed positioning will be disabled when to top element reach selected parent element vertically.'
    text:
      type: label
      label: 'Label'
