<?php

/**
 * @file
 * Contains tab_toolbar.module.
 */
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function tab_toolbar_theme($existing, $type, $theme, $path) {
  $items['tab_toolbar'] = [
    'variables' => ['primary' => [], 'secondary' => []],
  ];

  return $items;
}

/**
 * Implements hook_toolbar().
 */
function tab_toolbar_toolbar() {

  // Do not show tabs when on the admin theme.
  // TODO: Make this a configurable setting (and turned off by default).
  $active_theme = \Drupal::theme()->getActiveTheme()->getName();
  $admin_theme = \Drupal::config('system.theme')->get('admin');
  if ($active_theme == $admin_theme) {
    return;
  }

  $manager = \Drupal::service('plugin.manager.menu.local_task');
  $tasks = $manager->getLocalTasks(\Drupal::routeMatch()->getRouteName());

  $items['primary_tasks'] = array(
    '#type' => 'toolbar_item',
    'tab' => array(
      '#type' => 'link',
      '#title' => t('Page Actions'),
      '#url' => Url::fromRoute('<front>'),
      '#attributes' => array(
        'title' => t('Home page'),
        'class' => array('toolbar-icon', 'toolbar-icon-edit'),
      ),
    ),
    'tray' => array(
      '#heading' => t('Page actions'),
      'toolbar_actions' => array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => array('toolbar-menu-administration'),
        ),
        '#theme' => 'tab_toolbar',
        '#primary' => $tasks['tabs'],
      ),
    ),
    '#cache' => array(
      'contexts' => array('user.permissions', 'url.path'),
    ),
  );

  return $items;
}
